import type { Metadata } from 'next'
import { Comfortaa } from 'next/font/google'

import Layout from '@/components/layouts/Layout'
import './globals.css'

const comfortaa = Comfortaa({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'KastaShop',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode
}>) {
  return (
    <html lang='en'>
      <body className={comfortaa.className}>
        <Layout>{children}</Layout>
      </body>
    </html>
  )
}
